version: '3.8'

services:
  hyperbolic-inference:
    build: .
    ports:
      - "11434:11434"
    environment:
      - HYPERBOLIC_API_URL=https://api.hyperbolic.xyz/v1
      - HYPERBOLIC_API_KEY=${HYPERBOLIC_API_KEY}
      - HYPERBOLIC_MODEL=meta-llama/Llama-3.2-3B-Instruct
    restart: unless-stopped
