version: '3.8'

services:
  hyperbolic-inference:
    build: .
    ports:
      - "11434:11434"
      - "14444:11434"
    environment:
      - HYPERBOLIC_API_URL=${HYPERBOLIC_API_URL:-https://api.hyperbolic.xyz/v1}
      - HYPERBOLIC_API_KEY=${HYPERBOLIC_API_KEY}
      - HYPERBOLIC_MODEL=${HYPERBOLIC_MODEL:-meta-llama/Llama-3.2-3B-Instruct}
    command: ["gunicorn",
              "-w","1",
              "-k","gthread","--threads","8",
              "-b","0.0.0.0:11434",
              "--keep-alive","30",
              "--access-logfile","-","--error-logfile","-",
              "app:app"]
