services:
  kuzco-main:
    build: .
    container_name: kuzco-main
    network_mode: "host"     # atau gunakan bridge jika tidak butuh host mode
    privileged: true
    restart: always
    security_opt:
      - apparmor:unconfined
    environment:
      NODE_ENV: "production"
      CODE: "YOUR_WORKER_CODE"
      WORKER_NAME: "YOUR_WORKER_NAME"
      OLLAMA_HOST: "http://localhost:11434"    # make sure ini mengarah ke hyperbolic service
      OLLAMA_ORIGINS: "*"
      INFERENCE_ENGINE: "hyperbolic"
      CUDA_VISIBLE_DEVICES: "0"
