version: "3.8"
services:
  kuzco-main:
    build: .
    container_name: kuzco-main
    network_mode: "host"
    privileged: true
    restart: always
    environment:
      NODE_ENV: "production"
      CODE: "YOUR_WORKER_CODE"
      WORKER_NAME: "YOUR_WORKER_NAME"
      OLLAMA_HOST: "http://localhost:11434"
      CUDA_VISIBLE_DEVICES: "0"
    volumes:
      # Mount proc filesystem untuk system info commands
      - /proc:/proc:ro
      # Mount sys untuk PCI device access
      - /sys:/sys:ro
